---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dogs-cats
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/east-ga-atl-2302/dogs-cats
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
