---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dogs-cats
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/west-ca-sd-2301/dogs-cats/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
